name: a2a-environment
channels:
  - conda-forge
  - defaults
  - jupyter
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - pip:
    - -r requirements.txt

  # - pip:
  #   # Install the local project in editable mode with dev extras
  #   - -e .[dev]
